server:
  port: 8091

spring:
  application:
    name: segundo

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50
rest:
  timeout:
    connect: 3
    request: 3
    response: 5
    socket: 5

microservicio-uno:
  uri: http://localhost:8092
  endpoint:
    findAll: /user/find-all
